# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Update env file
        run: |
          cd my-website
          echo Hello, world!
          echo REACT_APP_PARSE_APP_ID=${{ secrets.REACT_APP_PARSE_APP_ID }} >> .env
          echo REACT_APP_PARSE_JS_KEY=${{ secrets.REACT_APP_PARSE_JS_KEY }} >> .env
          echo REACT_APP_PARSE_SERVER_URL=${{ secrets.REACT_APP_PARSE_SERVER_URL }} >> .env
