# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build
    - name: Deploy
      run: |
        cd my-website
        echo Hello, world!
        echo REACT_APP_PARSE_APP_ID=${{ secrets.REACT_APP_PARSE_APP_ID }} >> .env
        echo REACT_APP_PARSE_JS_KEY=${{ secrets.REACT_APP_PARSE_JS_KEY }} >> .env
        echo REACT_APP_PARSE_SERVER_URL=${{ secrets.REACT_APP_PARSE_SERVER_URL }} >> .env
        npm run deploy
